package com.shipaton.quotesofwisdom.ui.theme

import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Typography
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

data class AppThemePalette(
    val id: String,
    val name: String,
    val dominant: Color,
    val secondary: Color,
    val accent: Color,
    val isFree: Boolean = false
)

val AppThemes = listOf(
    AppThemePalette("parchment", "Parchment", Color(0xFFFFFDF7), Color(0xFF2E2A26), Color(0xFFB65435), true),
    AppThemePalette("midnight_gold", "Midnight Gold", Color(0xFF101820), Color(0xFFF2E9D8), Color(0xFFD9A441), true),
    AppThemePalette("sage_ink", "Sage Ink", Color(0xFFE8EFE5), Color(0xFF24322A), Color(0xFF7D4F50)),
    AppThemePalette("ocean_coral", "Ocean Coral", Color(0xFFE9F4F6), Color(0xFF12343B), Color(0xFFFF3827)),
    AppThemePalette("cherry_cream", "Cherry Cream", Color(0xFFFFF4E6), Color(0xFF4A1C2B), Color(0xFFD7263D)),
    AppThemePalette("lavender_ink", "Lavender Ink", Color(0xFFF0EAF7), Color(0xFF2B2140), Color(0xFF8D6AC8)),
    AppThemePalette("teal_copper", "Teal Copper", Color(0xFFE8F2F0), Color(0xFF173F3A), Color(0xFFC66A3D)),
    AppThemePalette("sand_navy", "Sand Navy", Color(0xFFF4E9D8), Color(0xFF172A3A), Color(0xFFBC6F33)),
    AppThemePalette("rosewood", "Rosewood", Color(0xFFF8ECEA), Color(0xFF45252A), Color(0xFFBF6E6A)),
    AppThemePalette("forest_ember", "Forest Ember", Color(0xFF14251D), Color(0xFFE8E1D4), Color(0xFFE56B3F)),
    AppThemePalette("ice_cobalt", "Ice Cobalt", Color(0xFFEAF3FF), Color(0xFF16213E), Color(0xFF2F6BFF)),
    AppThemePalette("espresso", "Espresso Cream", Color(0xFFF3E7D3), Color(0xFF33241C), Color(0xFFB8703C)),
    AppThemePalette("plum_champagne", "Plum Champagne", Color(0xFF2F1B2E), Color(0xFFF5E9DD), Color(0xFFD6A85F)),
    AppThemePalette("slate_mint", "Slate Mint", Color(0xFF202A33), Color(0xFFE8F1EC), Color(0xFF6FD0B0)),
    AppThemePalette("sunset_charcoal", "Sunset Charcoal", Color(0xFFFFE9DD), Color(0xFF2C2C2C), Color(0xFFFF2B0B)),
    AppThemePalette("burgundy_pearl", "Burgundy Pearl", Color(0xFFF7EFEA), Color(0xFF511F2B), Color(0xFFAE7D2A)),
    AppThemePalette("moss_clay", "Moss Clay", Color(0xFFEAE8D8), Color(0xFF2F3A2D), Color(0xFFB95C3D)),
    AppThemePalette("azure_lemon", "Azure Lemon", Color(0xFFE9F5FF), Color(0xFF15324A), Color(0xFFA78311)),
    AppThemePalette("graphite_lilac", "Graphite Lilac", Color(0xFF24242A), Color(0xFFF0EDF7), Color(0xFFB89CFF)),
    AppThemePalette("ivory_jade", "Ivory Jade", Color(0xFFFFFBEE), Color(0xFF18392B), Color(0xFFCC6D3D)),
    AppThemePalette("neon_noir", "Neon Noir", Color(0xFF0A0A0F), Color(0xFFF5F5F5), Color(0xFF39FF14)),
    AppThemePalette("cobalt_signal", "Cobalt Signal", Color(0xFF0A2463), Color(0xFFF6F7FB), Color(0xFFFFC857)),
    AppThemePalette("crimson_ink", "Crimson Ink", Color(0xFF1C0B0E), Color(0xFFF7E8EA), Color(0xFFFF4D6D)),
    AppThemePalette("electric_violet", "Electric Violet", Color(0xFF171221), Color(0xFFF4EEFF), Color(0xFFB86BFF)),
    AppThemePalette("carbon_cyan", "Carbon Cyan", Color(0xFF111820), Color(0xFFEAFBFF), Color(0xFF00D9FF)),
    AppThemePalette("obsidian_orange", "Obsidian Orange", Color(0xFF111111), Color(0xFFF5EEE7), Color(0xFFFF7A00)),
    AppThemePalette("royal_cyan", "Royal Cyan", Color(0xFF0D1B2A), Color(0xFFE0EAF3), Color(0xFF00B4D8)),
    AppThemePalette("ruby_sand", "Ruby Sand", Color(0xFFFFE8D6), Color(0xFF3B1725), Color(0xFFC9184A)),
    AppThemePalette("acid_plum", "Acid Plum", Color(0xFF24112F), Color(0xFFF6F0F8), Color(0xFFC8FF3D)),
    AppThemePalette("mono_red", "Mono Red", Color(0xFFF3F3F3), Color(0xFF161616), Color(0xFFE10600)),
    AppThemePalette("petrol_amber", "Petrol Amber", Color(0xFF0C2D33), Color(0xFFEAF2F2), Color(0xFFFFB000)),
    AppThemePalette("ink_pink", "Ink Pink", Color(0xFF16131A), Color(0xFFF6EEF4), Color(0xFFFF4FA3)),
    AppThemePalette("navy_mint", "Navy Mint", Color(0xFF071E3D), Color(0xFFEAF4F4), Color(0xFF2DE2A6)),
    AppThemePalette("charcoal_yellow", "Charcoal Yellow", Color(0xFF232323), Color(0xFFF3F1E8), Color(0xFFFFD400)),
    AppThemePalette("deep_teal_pink", "Teal Pink", Color(0xFF062F34), Color(0xFFEAF4F2), Color(0xFFFF5C8A)),
    AppThemePalette("black_cream_blue", "Black Blue", Color(0xFF0D0D10), Color(0xFFF4EFE4), Color(0xFF4D8DFF)),
    AppThemePalette("storm_orange", "Storm Orange", Color(0xFFE9EDF0), Color(0xFF1F2A35), Color(0xFFDC5B00)),
    AppThemePalette("oxblood_ice", "Oxblood Ice", Color(0xFF3A0D18), Color(0xFFF4F7FA), Color(0xFF7FDBFF)),
    AppThemePalette("ultraviolet_sand", "Ultraviolet Sand", Color(0xFFF5E7CF), Color(0xFF231A34), Color(0xFF7B2FFF)),
    AppThemePalette("copper_night", "Copper Night", Color(0xFF101721), Color(0xFFEDE6DD), Color(0xFFC87333)),
    AppThemePalette("mint_black_red", "Mint Red", Color(0xFFE5F7EF), Color(0xFF111817), Color(0xFFE63946)),
    AppThemePalette("scarlet_navy", "Scarlet Navy", Color(0xFFF3F6FA), Color(0xFF0B1F3A), Color(0xFFD90429)),
    AppThemePalette("gold_black_cream", "Cream Gold", Color(0xFFF8F1E1), Color(0xFF151515), Color(0xFFA7812F)),
    AppThemePalette("blueprint", "Blueprint", Color(0xFF0A3D91), Color(0xFFF2F7FF), Color(0xFFFFD166)),
    AppThemePalette("noir_rose", "Noir Rose", Color(0xFF0E0C10), Color(0xFFF5EEF2), Color(0xFFE07A9B)),
    AppThemePalette("pine_signal", "Pine Signal", Color(0xFF102A25), Color(0xFFE9F0EB), Color(0xFFFFC400)),
    AppThemePalette("magenta_stone", "Magenta Stone", Color(0xFFECE9ED), Color(0xFF27222A), Color(0xFFD81B60)),
    AppThemePalette("amber_cobalt", "Amber Cobalt", Color(0xFF0B1D51), Color(0xFFF1F5FF), Color(0xFFFFA000)),
    AppThemePalette("steel_lime", "Steel Lime", Color(0xFF1E2732), Color(0xFFE8EDF2), Color(0xFFB6FF3B)),
    AppThemePalette("violet_gold", "Violet Gold", Color(0xFF24113B), Color(0xFFF4EAF8), Color(0xFFFFC857)),
    AppThemePalette("coral_navy", "Coral Navy", Color(0xFFFFE8E2), Color(0xFF18243A), Color(0xFFFF272E)),
    AppThemePalette("emerald_cream", "Emerald Cream", Color(0xFF0D3327), Color(0xFFF6F0DE), Color(0xFF5CE1A6)),
    AppThemePalette("purple_copper", "Purple Copper", Color(0xFF251631), Color(0xFFF4ECF5), Color(0xFFD47A43)),
    AppThemePalette("cyan_charcoal", "Cyan Charcoal", Color(0xFFE8FAFC), Color(0xFF1E2B2F), Color(0xFF0098AD)),
    AppThemePalette("red_ivory", "Red Ivory", Color(0xFFFFF8EE), Color(0xFF3A1717), Color(0xFFD5202F)),
    AppThemePalette("indigo_coral", "Indigo Coral", Color(0xFF171A3F), Color(0xFFF5F1F7), Color(0xFFFF7262)),
    AppThemePalette("bronze_ink", "Bronze Ink", Color(0xFFF4E7D0), Color(0xFF28221C), Color(0xFFB06F32)),
    AppThemePalette("glacier_red", "Glacier Red", Color(0xFFEAF7FF), Color(0xFF19344C), Color(0xFFF04452)),
    AppThemePalette("walnut_sage", "Walnut Sage", Color(0xFF2D211C), Color(0xFFF0ECE3), Color(0xFF9DBB91)),
    AppThemePalette("aqua_plum", "Aqua Plum", Color(0xFFE5FAF5), Color(0xFF3D1F3A), Color(0xFF009B84)),
    AppThemePalette("lemon_midnight", "Lemon Midnight", Color(0xFFFFF7C7), Color(0xFF151A2B), Color(0xFF7E57C2)),
    AppThemePalette("raspberry_cream", "Raspberry Cream", Color(0xFFFFF1F4), Color(0xFF3E1728), Color(0xFFC2185B)),
    AppThemePalette("sapphire_peach", "Sapphire Peach", Color(0xFF102A56), Color(0xFFF8EFE7), Color(0xFFFF9E76)),
    AppThemePalette("jade_gold", "Jade Gold", Color(0xFF12372A), Color(0xFFF1EFE4), Color(0xFFE6B84A)),
    AppThemePalette("aubergine_mint", "Aubergine Mint", Color(0xFF32142F), Color(0xFFF0F7F2), Color(0xFF58C99A)),
    AppThemePalette("terracotta_sky", "Terracotta Sky", Color(0xFFF3DDD1), Color(0xFF253649), Color(0xFFD15430)),
    AppThemePalette("crimson_silver", "Crimson Silver", Color(0xFF2B0D16), Color(0xFFF0F2F4), Color(0xFFE23A52)),
    AppThemePalette("orchid_navy", "Orchid Navy", Color(0xFFF2E8F7), Color(0xFF17233F), Color(0xFFA751C5)),
    AppThemePalette("lagoon_sun", "Lagoon Sun", Color(0xFF083C45), Color(0xFFF3F6EE), Color(0xFFFFC928)),
    AppThemePalette("mocha_blue", "Mocha Blue", Color(0xFFF0E4D8), Color(0xFF30241E), Color(0xFF3478C5)),
    AppThemePalette("black_teal_orange", "Black Orange", Color(0xFF101415), Color(0xFFE8F4F2), Color(0xFFFF6B2C)),
    AppThemePalette("cream_violet_green", "Cream Green", Color(0xFFFFF5E6), Color(0xFF322447), Color(0xFF4A996E)),
    AppThemePalette("denim_copper", "Denim Copper", Color(0xFF172B46), Color(0xFFEAF0F6), Color(0xFFC97C48)),
    AppThemePalette("plum_lime", "Plum Lime", Color(0xFF2A1533), Color(0xFFF5F0F6), Color(0xFFA8E63A)),
    AppThemePalette("slate_orange", "Slate Orange", Color(0xFFE9EDF2), Color(0xFF263442), Color(0xFFE75100)),
    AppThemePalette("wine_mint", "Wine Mint", Color(0xFF461827), Color(0xFFF4EFEF), Color(0xFF7BD5B1)),
    AppThemePalette("white_black_cyan", "White Cyan", Color(0xFFFAFAFA), Color(0xFF151515), Color(0xFF009AB2)),
    AppThemePalette("marine_gold", "Marine Gold", Color(0xFF0B2B40), Color(0xFFEFF4F6), Color(0xFFDDAA35)),
    AppThemePalette("charcoal_coral", "Charcoal Coral", Color(0xFF24272B), Color(0xFFF2EEE9), Color(0xFFFF6F61)),
    AppThemePalette("espresso_mint", "Espresso Mint", Color(0xFF2C211B), Color(0xFFF4EDE5), Color(0xFF79D8B3)),
    AppThemePalette("storm_pink", "Storm Pink", Color(0xFFE8EBF0), Color(0xFF252A35), Color(0xFFE8498A)),
    AppThemePalette("obsidian_lime", "Obsidian Lime", Color(0xFF0C0D10), Color(0xFFF2F4F0), Color(0xFFB7F13A)),
    AppThemePalette("pearl_blue_red", "Pearl Red", Color(0xFFF7F7F1), Color(0xFF19385C), Color(0xFFD93445)),
    AppThemePalette("navy_orange_cream", "Navy Orange", Color(0xFF0C1F38), Color(0xFFF8F1E5), Color(0xFFFF8A34)),
    AppThemePalette("olive_violet", "Olive Violet", Color(0xFFEDEEDC), Color(0xFF31351F), Color(0xFF7C4DB5)),
    AppThemePalette("rust_ice", "Rust Ice", Color(0xFFF0F7FA), Color(0xFF40251F), Color(0xFFC75632)),
    AppThemePalette("ink_mustard", "Ink Mustard", Color(0xFF171A1E), Color(0xFFF4F0E8), Color(0xFFD9A514)),
    AppThemePalette("graphite_coral", "Graphite Coral", Color(0xFF27282E), Color(0xFFF1EEF0), Color(0xFFFF776B)),
    AppThemePalette("cobalt_mint", "Cobalt Mint", Color(0xFF113A72), Color(0xFFF0F5F7), Color(0xFF67D6B0)),
    AppThemePalette("plum_apricot", "Plum Apricot", Color(0xFFF8E8DC), Color(0xFF3B203B), Color(0xFFDE5621)),
    AppThemePalette("forest_gold", "Forest Gold", Color(0xFF102B22), Color(0xFFF1EFE5), Color(0xFFD9AC45)),
    AppThemePalette("cream_teal_magenta", "Cream Magenta", Color(0xFFFFF3E4), Color(0xFF184342), Color(0xFFD9468F)),
    AppThemePalette("midnight_peach", "Midnight Peach", Color(0xFF11192A), Color(0xFFF6EFE8), Color(0xFFFFA07D)),
    AppThemePalette("steel_cyan", "Steel Cyan", Color(0xFF29333D), Color(0xFFF0F4F6), Color(0xFF31C5DA)),
    AppThemePalette("raspberry_ink", "Raspberry Ink", Color(0xFF3B1025), Color(0xFFF6EEF2), Color(0xFFFF5E9C)),
    AppThemePalette("ivory_cobalt_orange", "Ivory Orange", Color(0xFFFFF8E8), Color(0xFF1C3764), Color(0xFFE66410)),
    AppThemePalette("pine_coral", "Pine Coral", Color(0xFF153229), Color(0xFFF2F0E8), Color(0xFFFF735D)),
    AppThemePalette("black_gold_red", "Black Gold", Color(0xFF0F0F10), Color(0xFFF3ECE0), Color(0xFFE9B13C)),
    AppThemePalette("lavender_navy_lime", "Lavender Lime", Color(0xFFF1ECFA), Color(0xFF1C2A4A), Color(0xFF679128)),
    AppThemePalette("chalk_burgundy", "Chalk Burgundy", Color(0xFFF5F2EA), Color(0xFF4C1E2C), Color(0xFFB96A70))
)

val DefaultTheme = AppThemes.first()

fun themeById(id: String): AppThemePalette = AppThemes.firstOrNull { it.id == id } ?: DefaultTheme

private fun appColorScheme(palette: AppThemePalette) = lightColorScheme(
    primary = palette.accent,
    onPrimary = palette.secondary,
    primaryContainer = palette.accent,
    onPrimaryContainer = palette.secondary,
    inversePrimary = palette.accent,
    secondary = palette.secondary,
    onSecondary = palette.dominant,
    secondaryContainer = palette.secondary,
    onSecondaryContainer = palette.dominant,
    tertiary = palette.accent,
    onTertiary = palette.secondary,
    tertiaryContainer = palette.accent,
    onTertiaryContainer = palette.secondary,
    background = palette.dominant,
    onBackground = palette.secondary,
    surface = palette.dominant,
    onSurface = palette.secondary,
    surfaceVariant = palette.secondary,
    onSurfaceVariant = palette.accent,
    surfaceTint = palette.accent,
    inverseSurface = palette.secondary,
    inverseOnSurface = palette.dominant,
    error = palette.accent,
    onError = palette.secondary,
    errorContainer = palette.accent,
    onErrorContainer = palette.secondary,
    outline = palette.accent,
    outlineVariant = palette.accent,
    scrim = palette.secondary,
    surfaceBright = palette.dominant,
    surfaceContainer = palette.dominant,
    surfaceContainerHigh = palette.dominant,
    surfaceContainerHighest = palette.dominant,
    surfaceContainerLow = palette.dominant,
    surfaceContainerLowest = palette.dominant,
    surfaceDim = palette.dominant,
    primaryFixed = palette.accent,
    primaryFixedDim = palette.accent,
    onPrimaryFixed = palette.secondary,
    onPrimaryFixedVariant = palette.secondary,
    secondaryFixed = palette.secondary,
    secondaryFixedDim = palette.secondary,
    onSecondaryFixed = palette.accent,
    onSecondaryFixedVariant = palette.accent,
    tertiaryFixed = palette.accent,
    tertiaryFixedDim = palette.accent,
    onTertiaryFixed = palette.secondary,
    onTertiaryFixedVariant = palette.secondary
)

@Composable
fun QuotesOfWisdomTheme(
    palette: AppThemePalette = DefaultTheme,
    content: @Composable () -> Unit
) {
    MaterialTheme(
        colorScheme = appColorScheme(palette),
        typography = Typography(),
        content = content
    )
}
